Refractor A Few Files For Readability And Perhaps A Bit More Professi…
oslabs-beta/sapling pull request #93
Opened 2021-10-14 21:03 UTC by hienqn

Hello friends!

Fellow Codesmith here! This project looks great! I would actually love to use this myself for my personal project. 

I've moved a few files and refractor a few other places to make the codebase looks a bit more professional (at least from my industry experience). I'll try to think of what could be added to make this extension better, but here is what I have in the meanwhile.

2021-10-15 10:05 UTC, antoniel approved these changes

2021-10-19 00:22 UTC, charlesgutwirth requested changes
@hienqn Really appreciate the great formatting and readability additions! Would you by chance be able to resubmit the pull request without the re-parsing on active file change? We've just decided that this feature would interfere with the user experience too much as it would constantly collapse the tree whenever the user opens new files. Thanks again for this request!

2021-10-19 20:01 UTC, hienqn commented
@charlesgutwirth Done! I've removed that feature! Thanks alot!

2021-10-22 18:31 UTC, charlesgutwirth approved these changes

2021-10-22 19:10 UTC, PLCoster approved these changes

2021-10-26 05:30 UTC, merged